### ISSUE TITLE
Don't work on my configuration.

### ISSUE THREAD

**Issue by G3N-es** [pytesNET/paw.designer#1]
Paw.designer looks really great, but...
Don't work on my configuration.
http://g3nshop.g3n.es/admin/designer don't print anything.

You can see the configuration directly on the site.
http://g3nshop.g3n.es/admin/
http://g3nshop.g3n.es/admin/developers

Thanks

**Comment by SamBrishes** [comment]
Hellow,

thanks for this issue. Please rename the main plugin folder within your `bl-plugins` directory from `paw.designer-master` into `paw-designer` and try it again.

Thanks.

Sincerely,
Sam.

**Comment by G3N-es** [comment]
Now can see it. Thanks :-).

**Comment by G3N-es** [comment]
You could include the indication in the readme.
Also when you indicate:
"You need a need to include" paw.designer "compatible themes, of course!" put below "The following themes supports the paw.designer environment AND plugin:

     fur.zerendo - A Blogger Template
"
This would simplify the installation understanding and make it more usable.

When I have time I will translate the language into Spanish

**Comment by SamBrishes** [comment]
Thanks, I'll change the README and add a list of compatible themes. (Another one is also coming soon) ^^

And I guess it's better to remove the static path and embed a dynamic solution. It would prevent such issues at all.

A spanisch translation would be really awesome. Thanks.

Sincerely,
Sam.

**Comment by G3N-es** [comment]
:-(
Fatal error:
in /bl-plugins/paw-designer/admin/theme.php on line 138

Fatal error: Uncaught Error: Access to undeclared static property: PawOption::$config in /home/jykk7sxz/en.g3n.es/bl-plugins/paw-designer/admin/theme.php:138 Stack trace: #0 /home/jykk7sxz/en.g3n.es/bl-plugins/paw-designer/plugin.php(380): include() #1 /home/jykk7sxz/en.g3n.es/bl-kernel/helpers/theme.class.php(229): PawDesigner->adminBodyEnd() #2 /home/jykk7sxz/en.g3n.es/bl-kernel/admin/themes/booty/index.php(90): Theme::plugins('adminBodyEnd') #3 /home/jykk7sxz/en.g3n.es/bl-kernel/boot/admin.php(92): include('/home/jykk7sxz/...') #4 /home/jykk7sxz/en.g3n.es/index.php(37): require('/home/jykk7sxz/...') #5 {main} thrown in /home/jykk7sxz/en.g3n.es/bl-plugins/paw-designer/admin/theme.php on line 138

**Comment by SamBrishes** [comment]
Hellow,

Thanks. I'm currently not at home, but I uploaded a small fix which should solve this issue. I'll test it later, when I'm back.

Sincerely,
Sam.

**Comment by G3N-es** [comment]
When you have time, you could solve it. There are people who ask for a menu manager. It is a pity that you have it. :-(

**Comment by SamBrishes** [comment]
Hellow,

Sorry for the long wait, but I uploaded a capable fix 14 days ago. So the issue should already be fixed using the current master branch. Nevertheless I changed the used solution, which also should prevent the error. Version 0.1.1 contains also a few other fixes too.

And why is it a "pity" that I have it? What do you mean?

Sincerely,
Sam.

**Comment by G3N-es** [comment]
I wanted to say that there are people who ask for a menu manager for bludit. However, that manager already exists, you created it (thanks for that). However, I could not recommend it because it did not work because of the bug. Well it's a shame that having worked so hard to create a solution, and being something that the community demands ... could not be used for a small bug.

I'm going to test it. Thanks again. It seems to me that you are doing a great job and touching many key points that bludit needed. The comments plugin was also needed. I will also test it when I can.


As soon as I can I'll pass the Spanish translations of your bludit plugins.

regards

**Comment by G3N-es** [comment]
Now work. Its great :-)

**Comment by SamBrishes** [comment]
Hellow,

I'm really sorry for that, I didn't know that a menu manager is such a big thing. For me it was just a nice feature, which doesn't help anybody, because currently only two themes implements this extension. I guess a core solution would be way better instead of a third party plugin, which the user needs to install next to the theme itself.

However, I will try to maintain the Plugin better in the future. Maybe also with some more functions to develop even better themes.

And thanks, Bludit was just something to play with. I didn't know that I would invest so many time in. :D

Sincerely,
Sam.
