### ISSUE TITLE
Error en alert message

### ISSUE THREAD

**Issue by G3N-es** [pytesNET/paw.designer#3]
Upon reviewing the translation I detected another small bug. The translations "pd-plugin-" do not load correctly. When updating the element in the alert message, the key appears instead of the value.

For example:

"pd-plugin-001"

instead of:

"The requested token is invalid or expired!"

**Comment by SamBrishes** [comment]
Hellow,

thanks for reporting. This issue has two causes:

- The form handler gets called before the language has been initialized.
- The wrong key name has been used on the respective `Alert` handler.

Both issues has been fixed, the master branch contains this fix as well as your translation.

Thanks.

Sincerely
Sam.
